// Generated by CoffeeScript 1.6.2
(function() {
  var app, express, jade, sass;

  express = require('express');

  jade = require('jade');

  sass = require('node-sass');

  app = module.exports = express();

  app.configure(function() {
    app.set('port', process.env.PORT || 5000);
    app.set('view engine', 'jade');
    app.set('view options', {
      layout: false
    });
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(sass.middleware({
      src: __dirname,
      dest: __dirname,
      debug: true
    }));
    return app.use(express["static"](__dirname + '/public'));
  });

  app.get("/", function(request, response) {
    return response.render('index');
  });

  app.listen(app.settings.port, function() {
    return console.log("Listening on " + app.settings.port);
  });

}).call(this);
