// Generated by CoffeeScript 1.6.2
(function() {
  var app, express, jade;

  express = require("express");

  jade = require("jade");

  app = module.exports = express();

  app.configure(function() {
    app.set('port', process.env.PORT || 5000);
    app.set('view engine', 'jade');
    app.set("view options", {
      layout: false
    });
    app.use(express.bodyParser());
    return app.use(express.methodOverride());
  });

  app.get("/", function(request, response) {
    return response.render('index');
  });

  app.listen(app.settings.port, function() {
    return console.log("Listening on " + app.settings.port);
  });

}).call(this);
